# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(ranger)
    library(recipes)
    library(workflows)
}
b <- board_folder(path = "vetiver_board")
v <- vetiver_pin_read(b, "fm_house_price_model", version = "20260918T062012Z-b7f51")

#* @plumber
function(pr) {
    pr |> vetiver_api(v)
}
